const SUPABASE_URL = "https://jjfqafbvyloaizkuxesg.supabase.co";
const API_KEY = "sb_publishable_W6DeRKEfwlfDQQU8BS5A6w_NI_kCuEe";
const FUNCTION_URL = `${SUPABASE_URL}/functions/v1/license-api`;
const AUTH_URL = `${SUPABASE_URL}/auth/v1`;
const APP_URL = "https://hassanhosseini205-wq.github.io/routineman-admin/";
const $ = (id) => document.getElementById(id);
let session = JSON.parse(localStorage.getItem("rm_admin_session") || "null");
let licenses = [], tiers = [];
const fa = new Intl.NumberFormat("fa-IR");
const tierNames = {bronze:"برنزی",silver:"نقره‌ای",gold:"طلایی"};
const statusNames = {active:"فعال",suspended:"معلق",revoked:"لغوشده"};
const featureNames = {habits:"مدیریت فعالیت‌ها",basic_stats:"آمار پایه",advanced_stats:"آمار حرفه‌ای",workout_manual:"برنامه تمرینی دستی",workout_coach:"مربی تمرینی",adaptive_progression:"پیشنهاد افزایش وزنه",pdf_csv:"گزارش PDF و CSV",encrypted_backup:"بکاپ رمزگذاری‌شده",multi_device_sync:"همگام‌سازی چند دستگاه",all_features:"تمام امکانات"};
function toast(message,error=false){const el=$("toast");el.textContent=message;el.className=`toast show${error?" error":""}`;clearTimeout(toast.t);toast.t=setTimeout(()=>el.className="toast",3200)}
function setBusy(form,busy){form.querySelectorAll("button,input,select,textarea").forEach(x=>x.disabled=busy)}
async function authRequest(path,body){const res=await fetch(`${AUTH_URL}${path}`,{method:"POST",headers:{apikey:API_KEY,"content-type":"application/json"},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.msg||data.error_description||"خطا در ورود");return data}
async function updatePassword(token,password){const res=await fetch(`${AUTH_URL}/user`,{method:"PUT",headers:{apikey:API_KEY,authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({password})});const data=await res.json();if(!res.ok)throw new Error(data.msg||data.error_description||"تغییر رمز انجام نشد");return data}
async function api(action,payload={}){if(!session?.access_token)throw new Error("نشست شما پایان یافته است");let res=await fetch(FUNCTION_URL,{method:"POST",headers:{apikey:API_KEY,authorization:`Bearer ${session.access_token}`,"content-type":"application/json"},body:JSON.stringify({action,...payload})});if(res.status===401&&session.refresh_token){try{const fresh=await authRequest("/token?grant_type=refresh_token",{refresh_token:session.refresh_token});session=fresh;localStorage.setItem("rm_admin_session",JSON.stringify(fresh));return api(action,payload)}catch{logout()}}const data=await res.json();if(!res.ok)throw new Error(errorText(data.error));return data}
function errorText(code){return ({admin_required:"این حساب دسترسی ادمین ندارد",duplicate_license:"این کد قبلاً ساخته شده",create_failed:"ساخت لایسنس انجام نشد",update_failed:"ذخیره تغییرات انجام نشد",device_update_failed:"آزادکردن دستگاه انجام نشد",tier_update_failed:"تغییر سطح انجام نشد",list_failed:"دریافت فهرست انجام نشد"})[code]||code||"خطای ناشناخته"}
function showApp(email){$("auth-view").classList.add("hidden");$("app-view").classList.remove("hidden");$("admin-email").textContent=email||session?.user?.email||"ادمین";loadAll()}
function logout(){session=null;localStorage.removeItem("rm_admin_session");$("app-view").classList.add("hidden");$("auth-view").classList.remove("hidden")}
async function loadAll(){try{const [a,b]=await Promise.all([api("list_licenses"),api("list_tiers")]);licenses=a.licenses||[];tiers=b.tiers||[];renderLicenses();renderTiers()}catch(e){toast(e.message,true);if(e.message.includes("ادمین"))logout()}}
function makeKey(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";const bytes=crypto.getRandomValues(new Uint8Array(20));const raw=[...bytes].map(b=>chars[b%chars.length]).join("");return `RM-${raw.slice(0,5)}-${raw.slice(5,10)}-${raw.slice(10,15)}-${raw.slice(15,20)}`}
function dateTimeInput(v){if(!v)return "";const d=new Date(v),pad=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
function dateFa(v){return v?new Intl.DateTimeFormat("fa-IR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"بدون محدودیت"}
function activeDevices(l){return (l.devices||[]).filter(d=>!d.revoked_at)}
function filtered(){const q=$("search").value.trim().toLowerCase(),s=$("status-filter").value;return licenses.filter(l=>(s==="all"||l.status===s)&&(!q||l.key_hint.toLowerCase().includes(q)||(l.devices||[]).some(d=>(d.device_label||"").toLowerCase().includes(q))))}
function renderLicenses(){const list=$("license-list"),data=filtered();$("stat-total").textContent=fa.format(licenses.length);$("stat-active").textContent=fa.format(licenses.filter(x=>x.status==="active").length);$("stat-gold").textContent=fa.format(licenses.filter(x=>x.tier_code==="gold").length);$("stat-devices").textContent=fa.format(licenses.reduce((n,x)=>n+activeDevices(x).length,0));if(!data.length){list.innerHTML='<div class="empty">هنوز لایسنسی مطابق این فیلتر وجود ندارد.</div>';return}list.innerHTML=data.map(l=>`<article class="license-card"><div class="license-top"><div><div class="license-code">••••-${escapeHtml(l.key_hint)}</div><div class="badges"><span class="badge ${l.tier_code}">${tierNames[l.tier_code]}</span><span class="badge ${l.status}">${statusNames[l.status]}</span></div></div><button class="btn secondary" data-edit="${l.id}">ویرایش</button></div><div class="meta-row"><span>دستگاه: ${fa.format(activeDevices(l).length)} از ${fa.format(l.max_devices)}</span><span>پایان: ${dateFa(l.expires_at)}</span><span>صدور: ${dateFa(l.created_at)}</span></div>${(l.devices||[]).length?`<div class="devices">${l.devices.map(d=>`<div class="device"><span>${escapeHtml(d.device_label||"دستگاه بدون نام")} ${d.revoked_at?"(آزادشده)":""}</span>${d.revoked_at?"":`<button data-revoke="${d.id}">آزادکردن</button>`}</div>`).join("")}</div>`:""}</article>`).join("");list.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openEdit(b.dataset.edit));list.querySelectorAll("[data-revoke]").forEach(b=>b.onclick=()=>revokeDevice(b.dataset.revoke))}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c])}
function openEdit(id){const l=licenses.find(x=>x.id===id);if(!l)return;$("edit-id").value=id;$("edit-tier").value=l.tier_code;$("edit-status").value=l.status;$("edit-max").value=l.max_devices;$("edit-expiry").value=dateTimeInput(l.expires_at);$("edit-dialog").showModal()}
async function revokeDevice(id){if(!confirm("این دستگاه از لایسنس آزاد شود؟"))return;try{await api("revoke_device",{device_id:id});toast("دستگاه آزاد شد");await loadAll()}catch(e){toast(e.message,true)}}
function renderTiers(){const box=$("tiers-list");if(!tiers.length){box.innerHTML='<div class="panel empty">سطحی دریافت نشد.</div>';return}const order={gold:0,silver:1,bronze:2};const sorted=[...tiers].sort((a,b)=>(order[a.code]??99)-(order[b.code]??99));box.innerHTML=sorted.map(t=>{const keys=Object.keys(featureNames);return `<article class="panel tier-card"><div class="tier-title"><div><span class="badge ${t.code}">${tierNames[t.code]}</span><h3>${escapeHtml(t.display_name)}</h3></div><label class="switch" aria-label="فعال بودن سطح"><input type="checkbox" data-active="${t.code}" ${t.active?"checked":""}><span></span></label></div><div class="feature-list">${keys.map(k=>`<label class="feature"><input type="checkbox" data-feature="${t.code}:${k}" ${t.features?.[k]?"checked":""}>${featureNames[k]}</label>`).join("")}</div><button class="btn primary" data-save-tier="${t.code}">ذخیره سطح ${tierNames[t.code]}</button></article>`}).join("");box.querySelectorAll("[data-save-tier]").forEach(b=>b.onclick=()=>saveTier(b.dataset.saveTier))}
async function saveTier(code){const features={};document.querySelectorAll(`[data-feature^="${code}:"]`).forEach(x=>features[x.dataset.feature.split(":")[1]]=x.checked);const active=document.querySelector(`[data-active="${code}"]`).checked;try{await api("update_tier",{tier:code,features,active});await loadAll();toast(`تغییرات سطح ${tierNames[code]} با موفقیت ذخیره شد`)}catch(e){toast(e.message,true)}}
$("login-form").onsubmit=async e=>{e.preventDefault();setBusy(e.currentTarget,true);try{const data=await authRequest("/token?grant_type=password",{email:$("login-email").value.trim(),password:$("login-password").value});session=data;localStorage.setItem("rm_admin_session",JSON.stringify(data));showApp(data.user?.email)}catch(err){toast(err.message,true)}finally{setBusy(e.currentTarget,false)}};
$("show-recovery").onclick=()=>$("recovery-form").classList.toggle("hidden");
$("recovery-form").onsubmit=async e=>{e.preventDefault();setBusy(e.currentTarget,true);try{await authRequest(`/recover?redirect_to=${encodeURIComponent(APP_URL)}`,{email:$("recovery-email").value.trim()});toast("اگر این ایمیل ثبت شده باشد، لینک بازیابی ارسال شد");$("recovery-form").classList.add("hidden")}catch(err){toast(err.message,true)}finally{setBusy(e.currentTarget,false)}};
$("password-form").onsubmit=async e=>{e.preventDefault();const password=$("new-password").value;if(password!==$("repeat-password").value){toast("تکرار رمز با رمز جدید یکسان نیست",true);return}setBusy(e.currentTarget,true);try{const token=new URLSearchParams(location.hash.slice(1)).get("access_token");if(!token)throw new Error("لینک بازیابی معتبر نیست یا منقضی شده است");await updatePassword(token,password);history.replaceState(null,"",location.pathname);session=null;localStorage.removeItem("rm_admin_session");$("password-view").classList.add("hidden");$("auth-view").classList.remove("hidden");toast("رمز جدید ذخیره شد؛ اکنون وارد حساب شو")}catch(err){toast(err.message,true)}finally{setBusy(e.currentTarget,false)}};
$("logout").onclick=logout;$("search").oninput=renderLicenses;$("status-filter").onchange=renderLicenses;$("close-dialog").onclick=()=>$("edit-dialog").close();
$("create-license").onsubmit=async e=>{e.preventDefault();const key=makeKey();setBusy(e.currentTarget,true);try{await api("create_license",{license_key:key,tier:$("new-tier").value,max_devices:Number($("new-max-devices").value),expires_at:$("new-expiry").value?new Date($("new-expiry").value).toISOString():null,customer_note:$("new-note").value});$("new-key").textContent=key;$("new-key-result").classList.remove("hidden");toast("لایسنس ساخته شد");await loadAll()}catch(err){toast(err.message,true)}finally{setBusy(e.currentTarget,false)}};
$("copy-key").onclick=async()=>{await navigator.clipboard.writeText($("new-key").textContent);toast("کد کپی شد")};
$("edit-form").onsubmit=async e=>{e.preventDefault();setBusy(e.currentTarget,true);try{await api("update_license",{license_id:$("edit-id").value,tier:$("edit-tier").value,status:$("edit-status").value,max_devices:Number($("edit-max").value),expires_at:$("edit-expiry").value?new Date($("edit-expiry").value).toISOString():null});$("edit-dialog").close();toast("تغییرات ذخیره شد");await loadAll()}catch(err){toast(err.message,true)}finally{setBusy(e.currentTarget,false)}};
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===b));const tier=b.dataset.tab==="tiers";$("licenses-tab").classList.toggle("hidden",tier);$("tiers-tab").classList.toggle("hidden",!tier);$("page-title").textContent=tier?"تنظیم سطح‌ها":"مدیریت لایسنس‌ها"});
function registerWebMCP(){const ctx=document.modelContext;if(!ctx?.registerTool)return;ctx.registerTool({name:"filter_licenses",title:"فیلتر لایسنس‌ها",description:"فهرست قابل مشاهده لایسنس‌ها را براساس وضعیت فیلتر می‌کند.",inputSchema:{type:"object",properties:{status:{type:"string",enum:["all","active","suspended","revoked"]}},required:["status"],additionalProperties:false},annotations:{readOnlyHint:true},execute:({status})=>{$("status-filter").value=status;renderLicenses();return{visible:filtered().length,status}}}).catch?.(()=>{});ctx.registerTool({name:"start_license_creation",title:"شروع ساخت لایسنس",description:"فرم ساخت لایسنس را با سطح انتخابی آماده می‌کند؛ هنوز لایسنس صادر نمی‌شود.",inputSchema:{type:"object",properties:{tier:{type:"string",enum:["bronze","silver","gold"]}},required:["tier"],additionalProperties:false},annotations:{readOnlyHint:false},execute:({tier})=>{$("new-tier").value=tier;window.scrollTo({top:0,behavior:"smooth"});return{ready:true,tier}}}).catch?.(()=>{})}
const recoveryParams=new URLSearchParams(location.hash.slice(1));
if(recoveryParams.get("type")==="recovery"&&recoveryParams.get("access_token")){$("auth-view").classList.add("hidden");$("password-view").classList.remove("hidden")}else if(session?.access_token)showApp(session.user?.email);
registerWebMCP();
