const SUPABASE_URL = "https://jjfqafbvyloaizkuxesg.supabase.co";
const API_KEY = "sb_publishable_W6DeRKEfwlfDQQU8BS5A6w_NI_kCuEe";
const FUNCTION_URL = `${SUPABASE_URL}/functions/v1/license-api`;
const AUTH_URL = `${SUPABASE_URL}/auth/v1`;
const APP_URL = "https://hassanhosseini205-wq.github.io/routineman-admin/";
const $ = (id) => document.getElementById(id);
let session = JSON.parse(localStorage.getItem("rm_admin_session") || "null");
let licenses = [], tiers = [];
const fa = new Intl.NumberFormat("fa-IR");
const tierNames = {bronze:"برنزی",silver:"نقره‌ای",gold:"طلایی"};
const statusNames = {active:"فعال",suspended:"معلق",revoked:"لغوشده"};
const featureNames = {habits:"مدیریت فعالیت‌ها",basic_stats:"آمار پایه",advanced_stats:"آمار حرفه‌ای",workout_manual:"برنامه تمرینی دستی",workout_coach:"مربی تمرینی",adaptive_progression:"پیشنهاد افزایش وزنه",pdf_csv:"گزارش PDF و CSV",encrypted_backup:"بکاپ رمزگذاری‌شده",multi_device_sync:"همگام‌سازی چند دستگاه",all_features:"تمام امکانات"};
function toast(message,error=false){const el=$("toast");el.textContent=message;el.className=`toast show${error?" error":""}`;clearTimeout(toast.t);toast.t=setTimeout(()=>el.className="toast",3200)}
function setBusy(form,busy){form.querySelectorAll("button,input,select,textarea").forEach(x=>x.disabled=busy)}
async function authRequest(path,body){const res=await fetch(`${AUTH_URL}${path}`,{method:"POST",headers:{apikey:API_KEY,"content-type":"application/json"},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.msg||data.error_description||"خطا در ورود");return data}
async function updatePassword(token,password){const res=await fetch(`${AUTH_URL}/user`,{method:"PUT",headers:{apikey:API_KEY,authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({password})});const data=await res.json();if(!res.ok)throw new Error(data.msg||data.error_description||"تغییر رمز انجام نشد");return data}
async function api(action,payload={}){if(!session?.access_token)throw new Error("نشست شما پایان یافته است");let res=await fetch(FUNCTION_URL,{method:"POST",headers:{apikey:API_KEY,authorization:`Bearer ${session.access_token}`,"content-type":"application/json"},body:JSON.stringify({action,...payload})});if(res.status===401&&session.refresh_token){try{const fresh=await authRequest("/token?grant_type=refresh_token",{refresh_token:session.refresh_token});session=fresh;localStorage.setItem("rm_admin_session",JSON.stringify(fresh));return api(action,payload)}catch{logout()}}const data=await res.json();if(!res.ok)throw new Error(errorText(data.error));return data}
function errorText(code){return ({admin_required:"این حساب دسترسی ادمین ندارد",duplicate_license:"این کد قبلاً ساخته شده",create_failed:"ساخت لایسنس انجام نشد",update_failed:"ذخیره تغییرات انجام نشد",device_update_failed:"عملیات دستگاه انجام نشد",tier_update_failed:"تغییر سطح انجام نشد",list_failed:"دریافت فهرست انجام نشد",delete_failed:"حذف لایسنس انجام نشد",trash_required:"ابتدا لایسنس را به سطل زباله منتقل کنید"})[code]||code||"خطای ناشناخته"}
function showApp(){$("auth-view").classList.add("hidden");$("app-view").classList.remove("hidden");loadAll()}
function logout(){session=null;localStorage.removeItem("rm_admin_session");$("app-view").classList.add("hidden");$("auth-view").classList.remove("hidden")}
async function loadAll(){try{const [a,b]=await Promise.all([api("list_licenses"),api("list_tiers")]);licenses=a.licenses||[];tiers=b.tiers||[];renderLicenses();renderTiers()}catch(e){toast(e.message,true);if(e.message.includes("ادمین"))logout()}}
function makeKey(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";const bytes=crypto.getRandomValues(new Uint8Array(20));const raw=[...bytes].map(b=>chars[b%chars.length]).join("");return `RM-${raw.slice(0,5)}-${raw.slice(5,10)}-${raw.slice(10,15)}-${raw.slice(15,20)}`}
const latinDigits=s=>String(s??"").replace(/[۰-۹]/g,d=>"۰۱۲۳۴۵۶۷۸۹".indexOf(d)).replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d));
const div=(a,b)=>Math.floor(a/b),mod=(a,b)=>a-Math.floor(a/b)*b;
function jalaliToGregorian(jy,jm,jd){jy+=1595;let days=-355668+365*jy+div(jy,33)*8+div(mod(jy,33)+3,4)+jd+(jm<7?(jm-1)*31:(jm-7)*30+186);let gy=400*div(days,146097);days=mod(days,146097);if(days>36524){gy+=100*div(--days,36524);days=mod(days,36524);if(days>=365)days++}gy+=4*div(days,1461);days=mod(days,1461);if(days>365){gy+=div(days-1,365);days=mod(days-1,365)}let gd=days+1;const sal=[0,31,(gy%4===0&&gy%100!==0)||gy%400===0?29:28,31,30,31,30,31,31,30,31,30,31];let gm=1;while(gm<=12&&gd>sal[gm])gd-=sal[gm++];return{gy,gm,gd}}
function persianParts(v){if(!v)return null;const parts=new Intl.DateTimeFormat("en-US-u-ca-persian",{timeZone:"Asia/Tehran",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(v));const get=t=>parts.find(p=>p.type===t)?.value;return{date:`${get("year")}/${get("month")}/${get("day")}`,time:`${get("hour")}:${get("minute")}`}}
function dateFa(v){const p=persianParts(v);return p?`${p.date} - ${p.time}`:"بدون محدودیت"}
function expiryIso(dateId,timeId){const rawDate=latinDigits($(dateId).value).trim(),rawTime=latinDigits($(timeId).value).trim();if(!rawDate&&!rawTime)return null;const m=rawDate.match(/^(\d{4})[\/-](\d{1,2})[\/-](\d{1,2})$/),t=rawTime.match(/^(\d{1,2}):(\d{2})$/);if(!m||!t)throw new Error("تاریخ را مثل 1405/06/22 و ساعت را مثل 17:10 وارد کن");const jy=+m[1],jm=+m[2],jd=+m[3],hh=+t[1],mm=+t[2];if(jm<1||jm>12||jd<1||jd>(jm<=6?31:jm<=11?30:30)||hh>23||mm>59)throw new Error("تاریخ یا ساعت پایان معتبر نیست");const g=jalaliToGregorian(jy,jm,jd);return new Date(Date.UTC(g.gy,g.gm-1,g.gd,hh-3,mm-30)).toISOString()}
function activeDevices(l){return (l.devices||[]).filter(d=>!d.revoked_at)}
function filtered(){const q=$("search").value.trim().toLowerCase(),s=$("status-filter").value,t=$("tier-filter").value,e=$("expiry-filter").value,d=$("device-filter").value,now=Date.now(),week=7*864e5;return licenses.filter(l=>{const active=activeDevices(l).length,end=l.expires_at?new Date(l.expires_at).getTime():null;const expiryOk=e==="all"||(e==="expired"&&end&&end<=now)||(e==="soon"&&end&&end>now&&end<=now+week)||(e==="valid"&&end&&end>now+week)||(e==="unlimited"&&!end);const deviceOk=d==="all"||(d==="none"&&active===0)||(d==="available"&&active<l.max_devices)||(d==="full"&&active>=l.max_devices);return !l.deleted_at&&(s==="all"||l.status===s)&&(t==="all"||l.tier_code===t)&&expiryOk&&deviceOk&&(!q||l.key_hint.toLowerCase().includes(q)||(l.customer_name||"").toLowerCase().includes(q)||(l.customer_phone||"").includes(q)||(l.devices||[]).some(x=>(x.device_label||"").toLowerCase().includes(q)))})}
function renderLicenses(){const list=$("license-list"),data=filtered(),live=licenses.filter(x=>!x.deleted_at),now=Date.now(),week=7*864e5;$("stat-total").textContent=fa.format(live.length);$("stat-active").textContent=fa.format(live.filter(x=>x.status==="active").length);$("stat-devices").textContent=fa.format(live.reduce((n,x)=>n+activeDevices(x).length,0));$("stat-gold").textContent=fa.format(live.filter(x=>x.tier_code==="gold").length);$("stat-silver").textContent=fa.format(live.filter(x=>x.tier_code==="silver").length);$("stat-bronze").textContent=fa.format(live.filter(x=>x.tier_code==="bronze").length);const expired=live.filter(l=>l.expires_at&&new Date(l.expires_at).getTime()<=now).length,soon=live.filter(l=>l.expires_at&&new Date(l.expires_at).getTime()>now&&new Date(l.expires_at).getTime()<=now+week).length,alert=$("expiry-alert");alert.classList.toggle("hidden",!expired&&!soon);alert.classList.toggle("danger",expired>0);alert.textContent=expired?`${fa.format(expired)} لایسنس منقضی شده و ${fa.format(soon)} لایسنس نزدیک پایان است`:`${fa.format(soon)} لایسنس تا ۷ روز آینده پایان می‌یابد`;if(!data.length){list.innerHTML='<div class="empty">لایسنسی مطابق این فیلتر پیدا نشد.</div>';return}list.innerHTML=data.map(l=>{const end=l.expires_at?new Date(l.expires_at).getTime():null,expiryClass=end&&end<=now?" expired":end&&end<=now+week?" expiring":"";return `<article class="license-card${expiryClass}"><div class="license-top"><div><div class="license-code">••••-${escapeHtml(l.key_hint)}</div><div class="badges"><span class="badge ${l.tier_code}">${tierNames[l.tier_code]}</span><span class="badge ${l.status}">${statusNames[l.status]}</span></div></div><button class="btn secondary" data-edit="${l.id}">ویرایش</button></div>${l.customer_name||l.customer_phone?`<div class="customer-line">${escapeHtml(l.customer_name||"بدون نام")}${l.customer_phone?` — ${escapeHtml(l.customer_phone)}`:""}${l.purchase_amount!=null?` — ${fa.format(l.purchase_amount)} تومان`:""}</div>`:""}<div class="meta-row"><span>دستگاه: ${fa.format(activeDevices(l).length)} از ${fa.format(l.max_devices)}</span><span>پایان: ${dateFa(l.expires_at)}</span><span>صدور: ${dateFa(l.created_at)}</span></div>${(l.devices||[]).length?`<div class="devices">${l.devices.map(d=>`<div class="device ${d.blocked_at?"blocked":""}"><div><strong>${escapeHtml(d.device_label||"دستگاه بدون نام")}</strong><small>آخرین اتصال: ${dateFa(d.last_checked_at)}</small></div>${d.blocked_at?`<span class="blocked-label">مسدود</span>`:`<div class="device-actions"><button data-release="${d.id}">آزادکردن</button><button class="danger-mini" data-block="${d.id}">مسدودکردن</button></div>`}</div>`).join("")}</div>`:""}</article>`}).join("");list.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openEdit(b.dataset.edit));list.querySelectorAll("[data-release]").forEach(b=>b.onclick=()=>releaseDevice(b.dataset.release));list.querySelectorAll("[data-block]").forEach(b=>b.onclick=()=>blockDevice(b.dataset.block))}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c])}
function openEdit(id){const l=licenses.find(x=>x.id===id);if(!l)return;$("edit-id").value=id;$("edit-tier").value=l.tier_code;$("edit-status").value=l.status;$("edit-max").value=l.max_devices;$("edit-customer-name").value=l.customer_name||"";$("edit-customer-phone").value=l.customer_phone||"";$("edit-purchase-amount").value=l.purchase_amount??"";const p=persianParts(l.expires_at);$("edit-expiry-date").value=p?.date||"";$("edit-expiry-time").value=p?.time||"";$("edit-dialog").showModal()}
async function releaseDevice(id){if(!confirm("این دستگاه آزاد شود؟ دستگاه می‌تواند دوباره فعال شود."))return;try{await api("release_device",{device_id:id});toast("دستگاه آزاد شد");await loadAll()}catch(e){toast(e.message,true)}}
async function blockDevice(id){if(!confirm("این دستگاه مسدود شود؟ با همین شناسه دوباره فعال نخواهد شد."))return;try{await api("block_device",{device_id:id});toast("دستگاه مسدود شد");await loadAll()}catch(e){toast(e.message,true)}}
async function trashLicense(){const id=$("edit-id").value;if(!confirm("این لایسنس به سطل زباله منتقل شود؟"))return;try{await api("trash_license",{license_id:id});$("edit-dialog").close();toast("لایسنس به سطل زباله منتقل شد");await loadAll()}catch(e){toast(e.message,true)}}
async function loadTrash(){const box=$("trash-list");box.innerHTML='<div class="empty">درحال دریافت…</div>';try{const data=await api("list_trash");box.innerHTML=(data.licenses||[]).map(l=>`<article class="license-card trashed"><div class="license-top"><div><div class="license-code">••••-${escapeHtml(l.key_hint)}</div><small>${escapeHtml(l.customer_name||"بدون نام")} — حذف: ${dateFa(l.deleted_at)}</small></div><div class="trash-actions"><button class="btn secondary" data-restore="${l.id}">بازیابی</button><button class="btn danger-outline" data-delete-forever="${l.id}">حذف دائمی</button></div></div></article>`).join("")||'<div class="empty">سطل زباله خالی است.</div>';box.querySelectorAll("[data-restore]").forEach(b=>b.onclick=()=>restoreLicense(b.dataset.restore));box.querySelectorAll("[data-delete-forever]").forEach(b=>b.onclick=()=>deleteForever(b.dataset.deleteForever))}catch(e){box.innerHTML='<div class="empty">دریافت سطل زباله انجام نشد.</div>';toast(e.message,true)}}
async function restoreLicense(id){if(!confirm("لایسنس بازیابی شود؟"))return;try{await api("restore_license",{license_id:id});toast("لایسنس بازیابی شد");await loadAll();await loadTrash()}catch(e){toast(e.message,true)}}
async function deleteForever(id){if(!confirm("حذف دائمی قابل بازگشت نیست. مطمئنی؟"))return;try{await api("delete_license_permanently",{license_id:id});toast("لایسنس برای همیشه حذف شد");await loadTrash()}catch(e){toast(e.message,true)}}
function renderTiers(){const box=$("tiers-list");if(!tiers.length){box.innerHTML='<div class="panel empty">سطحی دریافت نشد.</div>';return}const order={gold:0,silver:1,bronze:2};const sorted=[...tiers].sort((a,b)=>(order[a.code]??99)-(order[b.code]??99));box.innerHTML=sorted.map(t=>{const keys=Object.keys(featureNames);return `<article class="panel tier-card ${t.active?"":"tier-disabled"}" data-tier-card="${t.code}"><div class="tier-title"><h3 class="tier-name ${t.code}">${tierNames[t.code]}</h3><label class="switch" aria-label="فعال بودن سطح"><input type="checkbox" data-active="${t.code}" ${t.active?"checked":""}><span></span></label></div><div class="feature-list">${keys.map(k=>`<label class="feature"><input type="checkbox" data-feature="${t.code}:${k}" ${t.features?.[k]?"checked":""}>${featureNames[k]}</label>`).join("")}</div><button class="btn primary" data-save-tier="${t.code}">ذخیره سطح ${tierNames[t.code]}</button></article>`}).join("");box.querySelectorAll("[data-active]").forEach(x=>x.onchange=()=>document.querySelector(`[data-tier-card="${x.dataset.active}"]`).classList.toggle("tier-disabled",!x.checked));box.querySelectorAll("[data-save-tier]").forEach(b=>b.onclick=()=>saveTier(b.dataset.saveTier))}
async function saveTier(code){const features={};document.querySelectorAll(`[data-feature^="${code}:"]`).forEach(x=>features[x.dataset.feature.split(":")[1]]=x.checked);const active=document.querySelector(`[data-active="${code}"]`).checked;try{await api("update_tier",{tier:code,features,active});await loadAll();toast(`تغییرات سطح ${tierNames[code]} با موفقیت ذخیره شد`)}catch(e){toast(e.message,true)}}
$("login-form").onsubmit=async e=>{e.preventDefault();setBusy(e.currentTarget,true);try{const data=await authRequest("/token?grant_type=password",{email:$("login-email").value.trim(),password:$("login-password").value});session=data;localStorage.setItem("rm_admin_session",JSON.stringify(data));showApp(data.user?.email)}catch(err){toast(err.message,true)}finally{setBusy(e.currentTarget,false)}};
$("show-recovery").onclick=()=>$("recovery-form").classList.toggle("hidden");
$("recovery-form").onsubmit=async e=>{e.preventDefault();setBusy(e.currentTarget,true);try{await authRequest(`/recover?redirect_to=${encodeURIComponent(APP_URL)}`,{email:$("recovery-email").value.trim()});toast("اگر این ایمیل ثبت شده باشد، لینک بازیابی ارسال شد");$("recovery-form").classList.add("hidden")}catch(err){toast(err.message,true)}finally{setBusy(e.currentTarget,false)}};
$("password-form").onsubmit=async e=>{e.preventDefault();const password=$("new-password").value;if(password!==$("repeat-password").value){toast("تکرار رمز با رمز جدید یکسان نیست",true);return}setBusy(e.currentTarget,true);try{const token=new URLSearchParams(location.hash.slice(1)).get("access_token");if(!token)throw new Error("لینک بازیابی معتبر نیست یا منقضی شده است");await updatePassword(token,password);history.replaceState(null,"",location.pathname);session=null;localStorage.removeItem("rm_admin_session");$("password-view").classList.add("hidden");$("auth-view").classList.remove("hidden");toast("رمز جدید ذخیره شد؛ اکنون وارد حساب شو")}catch(err){toast(err.message,true)}finally{setBusy(e.currentTarget,false)}};
$("logout").onclick=logout;$("search").oninput=renderLicenses;["status-filter","tier-filter","expiry-filter","device-filter"].forEach(id=>$(id).onchange=renderLicenses);$("close-dialog").onclick=()=>$("edit-dialog").close();$("trash-license").onclick=trashLicense;$("refresh-trash").onclick=loadTrash;
$("create-license").onsubmit=async e=>{e.preventDefault();const key=makeKey();setBusy(e.currentTarget,true);try{await api("create_license",{license_key:key,tier:$("new-tier").value,max_devices:Number($("new-max-devices").value),expires_at:expiryIso("new-expiry-date","new-expiry-time"),customer_name:$("new-customer-name").value,customer_phone:$("new-customer-phone").value,purchase_amount:$("new-purchase-amount").value,customer_note:$("new-note").value});$("new-key").textContent=key;$("new-key-result").classList.remove("hidden");toast("لایسنس ساخته شد");await loadAll()}catch(err){toast(err.message,true)}finally{setBusy(e.currentTarget,false)}};
$("copy-key").onclick=async()=>{await navigator.clipboard.writeText($("new-key").textContent);toast("کد کپی شد")};
$("edit-form").onsubmit=async e=>{e.preventDefault();setBusy(e.currentTarget,true);try{await api("update_license",{license_id:$("edit-id").value,tier:$("edit-tier").value,status:$("edit-status").value,max_devices:Number($("edit-max").value),expires_at:expiryIso("edit-expiry-date","edit-expiry-time"),customer_name:$("edit-customer-name").value,customer_phone:$("edit-customer-phone").value,purchase_amount:$("edit-purchase-amount").value});$("edit-dialog").close();toast("تغییرات ذخیره شد");await loadAll()}catch(err){toast(err.message,true)}finally{setBusy(e.currentTarget,false)}};
document.querySelectorAll("[data-renew]").forEach(b=>b.onclick=async()=>{if(!confirm(`لایسنس ${b.textContent} تمدید شود؟`))return;b.disabled=true;try{await api("renew_license",{license_id:$("edit-id").value,days:Number(b.dataset.renew)});$("edit-dialog").close();toast("لایسنس تمدید شد");await loadAll()}catch(e){toast(e.message,true)}finally{b.disabled=false}});
const auditNames={create_license:"ساخت لایسنس",update_license:"ویرایش لایسنس",renew_license:"تمدید لایسنس",release_device:"آزادکردن دستگاه",block_device:"مسدودکردن دستگاه",trash_license:"انتقال به سطل زباله",restore_license:"بازیابی لایسنس",delete_license_permanently:"حذف دائمی لایسنس",update_tier:"تغییر سطح"};
async function loadAudit(){const box=$("audit-list");box.innerHTML='<div class="empty">درحال دریافت تاریخچه…</div>';try{const data=await api("list_audit");box.innerHTML=(data.audit||[]).map(x=>`<div class="audit-row"><time>${dateFa(x.created_at)}</time><div><strong>${auditNames[x.action]||escapeHtml(x.action)}</strong><small>${x.license_id?`شناسه لایسنس: ${escapeHtml(x.license_id)}`:"تغییر عمومی سیستم"}</small></div></div>`).join("")||'<div class="empty">هنوز تغییری ثبت نشده است.</div>'}catch(e){box.innerHTML='<div class="empty">دریافت تاریخچه انجام نشد.</div>';toast(e.message,true)}}
$("refresh-audit").onclick=loadAudit;
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===b));const tab=b.dataset.tab;$("licenses-tab").classList.toggle("hidden",tab!=="licenses");$("tiers-tab").classList.toggle("hidden",tab!=="tiers");$("audit-tab").classList.toggle("hidden",tab!=="audit");$("trash-tab").classList.toggle("hidden",tab!=="trash");if(tab==="audit")loadAudit();if(tab==="trash")loadTrash()});
function registerWebMCP(){const ctx=document.modelContext;if(!ctx?.registerTool)return;ctx.registerTool({name:"filter_licenses",title:"فیلتر لایسنس‌ها",description:"فهرست قابل مشاهده لایسنس‌ها را براساس وضعیت فیلتر می‌کند.",inputSchema:{type:"object",properties:{status:{type:"string",enum:["all","active","suspended","revoked"]}},required:["status"],additionalProperties:false},annotations:{readOnlyHint:true},execute:({status})=>{$("status-filter").value=status;renderLicenses();return{visible:filtered().length,status}}}).catch?.(()=>{});ctx.registerTool({name:"start_license_creation",title:"شروع ساخت لایسنس",description:"فرم ساخت لایسنس را با سطح انتخابی آماده می‌کند؛ هنوز لایسنس صادر نمی‌شود.",inputSchema:{type:"object",properties:{tier:{type:"string",enum:["bronze","silver","gold"]}},required:["tier"],additionalProperties:false},annotations:{readOnlyHint:false},execute:({tier})=>{$("new-tier").value=tier;window.scrollTo({top:0,behavior:"smooth"});return{ready:true,tier}}}).catch?.(()=>{})}
const recoveryParams=new URLSearchParams(location.hash.slice(1));
if(recoveryParams.get("type")==="recovery"&&recoveryParams.get("access_token")){$("auth-view").classList.add("hidden");$("password-view").classList.remove("hidden")}else if(session?.access_token)showApp(session.user?.email);
registerWebMCP();
